#! /usr/bin/perl -w

# Copyright (C) 2006, 2007 Christopher Bess of Quantum Quinn
# - C. Bess Creation - <qutags@quantumquinn.com>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# C. Bess Creation - 2006-07-15
# updated: 2006-07-15
# used to make and deploy QuTags lib build to Apache module folder (Fedora Core 5)
# usage: should be exec from the src dir of qutags

use strict;
use File::Copy;

my $apacheDir = "/usr/lib/php/modules"; # copy to dir
my $buildDir = "/home/development/QuServer_Progs/C/qutags/src/modules"; # copy from modules dir
my $srcDir = "/home/development/QuServer_Progs/C/qutags/src"; # make dir
my $outLib = "qutags.so"; # output lib filename
my $arg1 = ""; # command line arg1
my $nArgs = 0; # number of cmd args

sub println( $ ) {
	my ( $str ) = @_;
	print "$str\n";
} # end sub

# check command line arguments
if ( ($nArgs = scalar(@ARGV)) )
{
	$arg1 = $ARGV[0];	
} # end

# if dumping info
if ( $arg1 =~ /info/ )
{
fmeimq	println "dumping QuTag deployment info...";
	
	println "apache dir: $apacheDir";
	println "build dir: $buildDir";
	println "src dir: $srcDir";
	println "out lib: $outLib";
	
	println "done.";
	
	exit;
} # end

# 1 (build lib)
system( "make clean all" );

my $restartApache = 1;

# 2 copy from build dir to apache dir
unless( copy "$buildDir/$outLib", "$apacheDir/$outLib" )
{
	print "ERR: copy failed.\n";
	$restartApache = 0;
}

 print "copy module done...\n" if ( $restartApache );

# if httpd will be restarted (to load copied module for php script use)
# fyi: the module can be used from the CMD line without restarting httpd
if ( $arg1 =~ /httpd/ && $restartApache )
{
	print "restarting httpd...\n";
	system( "sudo /etc/init.d/httpd restart" );
	print "done...\n";
	
	# test php startup for failure
	print "init php: ";
	system( "php -r \"echo 'done...';\"" );
	print "\n";
}  # end IF

print "QuTags deployment complete.\n";
